### ISSUE TITLE
Error finding test.ged file

### ISSUE THREAD

**Issue by NickRance** [gthole/gedgo#10]
Thanks for your help with the last issue @gthole . Unfortunately, I'm still having issues getting the tests to pass, this time there's an issue finding the test.ged file in the static folder.

- Nick

**Console Log**

docker-compose run app ./test.sh
Starting redis ... done
Starting db    ... done
Creating test database for alias 'default'...
EEEEEEEE

======================================================================
ERROR: test_comment_gedcom (app.gedgo.tests.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 50, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_comment_person (app.gedgo.tests.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 50, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_pages_load (app.gedgo.tests.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 50, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_requires_login (app.gedgo.tests.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 50, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_upload_file (app.gedgo.tests.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 50, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_family_import (app.gedgo.tests.UpdateGedcom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 16, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_person_import (app.gedgo.tests.UpdateGedcom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 16, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

======================================================================
ERROR: test_update_from_gedcom (app.gedgo.tests.UpdateGedcom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/gedgo/tests.py", line 16, in setUp
    update(None, self.file_, verbose=False)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 21, in __init__
    self.file = open(file_name_or_stream, 'rU')
IOError: [Errno 2] No such file or directory: 'gedgo/static/test/test.ged'

----------------------------------------------------------------------
Ran 8 tests in 0.293s

FAILED (errors=8)
Destroying test database for alias 'default'...

**Comment by gthole** [comment]
[Fixed!](https://github.com/gthole/gedgo/commit/cd14f4a90251c59897bc8527f84364e4d19b53c0)  Give it a try now, and if it still doesn't work, just comment here and I'll re-open the issue.  Thanks for your persistence.
