### ISSUE TITLE
Importing Gedcom file exported from MyHeritage

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [gthole/gedgo#15]
```shell_session
$ sudo docker-compose run app python manage.py add_gedcom Family.ged
```
 > SyntaxError: Bad GEDCOM syntax in line: '1 _PROJECT_GUID 55019E4A35901490050E549C539F214F

Details : 
<details>

```
Starting redis ... done
Starting db    ... done
Parsing content
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/gedgo/management/commands/add_gedcom.py", line 24, in handle
    update(None, file_name)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/app/gedgo/gedcom_update.py", line 20, in update
    parsed = GedcomParser(file_name)
  File "/app/gedgo/gedcom_parser.py", line 24, in __init__
    self.__parse()
  File "/app/gedgo/gedcom_parser.py", line 33, in __parse
    tag, entry = self.__parse_element(line)
  File "/app/gedgo/gedcom_parser.py", line 66, in __parse_element
    _, child_element = self.__parse_element(next_line)
  File "/app/gedgo/gedcom_parser.py", line 46, in __parse_element
    raise SyntaxError("Bad GEDCOM syntax in line: '%s'" % line)
SyntaxError: Bad GEDCOM syntax in line: '1 _PROJECT_GUID 55019E4A35901490050E549C539F214F
'
```

</details>

**Comment by gthole** [comment]
Fixed with 1e2f4c0.
