### ISSUE TITLE
Multiple issues running docker-compose up

### ISSUE THREAD

**Issue by aleksas** [gthole/gedgo#16]
- Missing `.env` file referenced [here](https://github.com/gthole/gedgo/blob/a2561f443fe3e012386fc9e346720ca51062055f/docker-compose.yml#L6) causing `docker-compose up` command to fail.
- [`app`](https://github.com/gthole/gedgo/blob/master/docker-compose.yml#L3) container unable to modifiy `.files`, `.data`  directory content - permission denied
```sh
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 423, in check
    databases=databases,
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/caches.py", line 63, in check_file_based_cache_is_absolute
    cache = caches[alias]
  File "/usr/local/lib/python3.7/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/usr/local/lib/python3.7/site-packages/django/core/cache/__init__.py", line 44, in create_connection
    return backend_cls(location, params)
  File "/usr/local/lib/python3.7/site-packages/django/core/cache/backends/filebased.py", line 23, in __init__
    self._createdir()
  File "/usr/local/lib/python3.7/site-packages/django/core/cache/backends/filebased.py", line 121, in _createdir
    os.makedirs(self._dir, 0o700, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/.files/research_preview'
``` 
  - even if corresponding host directories are chmod'ed to 777 web page displays error:
![Screenshot from 2021-08-21 19-05-59](https://user-images.githubusercontent.com/594470/130327952-ab8c22b4-1a69-4f3b-9aca-82459afdcb3a.png)

**Comment by herrxyz** [comment]
got the same problem, docker-compose build not working
from docker hub I miss the correct parameters to run it

**Comment by Sternbach-Software** [comment]
In settings.py, I replaced the caches with
```
'research_preview': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache'
    },
```
However, I still had some build issues. Tried replacing the dropbox requirement with ```dropbox==11.36.0```. Got some SSL error.
